
build: off
stack: node 8
skip_tags: true
environment:
  matrix:
#      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#        ADO_ARTIFACTORY_SKIP_TESTS: docker
      - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        ADO_ARTIFACTORY_SKIP_TESTS: nuget

  nodejs_version: "8"
  ADO_ARTIFACTORY_URL:
    secure: RIh0gGFDn2JAnLUEEqLsQnZ5H3XFWg1s+Qq8Z4i+Xu+FtQf6Tsu2AnfY4/6AaXJ8
  ADO_ARTIFACTORY_USERNAME:
    secure: YEB5Wiv9a2vNpUhy+MfL+A==
  ADO_ARTIFACTORY_PASSWORD:
    secure: Um8o75MQIieSavIemF4ySA==
  ADO_ARTIFACTORY_DOCKER_DOMAIN:
    secure: ppjr6mrLIKXVptLX8WPOlffTwOLtRIoaIpsVEvmje/9mDtLojTqpwI9OIC5VZnx1
  ADO_ARTIFACTORY_DOCKER_REPO:
    secure: UjixvF6E1Bp1p8zgPRLCVA==

install:
- npm i -gq jfrog-cli-go
- npm i -gq tfx-cli
- sh: sudo pip install conan==1.21.0 -q
- cmd: pip install conan==1.21.0 -q
- cmd: nuget update -self

services:
- docker

test_script:
- node --version
- npm --version
#- npm run create # Make sure that that the extension can be created
- npm t
